# Generated by Django 3.2.9 on 2022-02-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
    ]
