# Generated by Django 3.2.9 on 2022-02-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_remember_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='remember_me',
        ),
    ]
