# Generated by Django 3.2.9 on 2022-02-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
